"""Generate index pages for documentation sections."""
from __future__ import annotations
import logging
from pathlib import Path

from .markdown_writer import sanitize_filename

logger = logging.getLogger(__name__)


def generate_index_pages(output_dir: Path, project_name: str) -> list[Path]:
    """Generate index.md files for all documentation sections."""
    generated: list[Path] = []
    docs_dir = output_dir / "docs"

    # Main index
    main_index = _generate_main_index(docs_dir, project_name)
    if main_index:
        generated.append(main_index)

    # Section indices
    sections = [
        ("generated/developer", "Developer Guide",
         "Technical documentation for developers working on this project."),
        ("generated/api", "API Reference",
         "Complete API reference documentation for integrating with this project."),
        ("generated/user", "User Guide",
         "User-facing documentation and tutorials."),
        ("manual", "Manual Pages",
         "Manually maintained documentation pages."),
    ]

    for section_path, title, description in sections:
        section_dir = docs_dir / section_path
        if section_dir.exists():
            idx = _generate_section_index(section_dir, section_path, title, description)
            if idx:
                generated.append(idx)

    # Sub-section indices (classes/, modules/, etc.)
    gen_dir = docs_dir / "generated"
    if gen_dir.exists():
        for stakeholder_dir in gen_dir.iterdir():
            if not stakeholder_dir.is_dir():
                continue
            for sub_dir in stakeholder_dir.iterdir():
                if not sub_dir.is_dir():
                    continue
                rel = sub_dir.relative_to(docs_dir)
                title = sub_dir.name.replace("-", " ").replace("_", " ").title()
                idx = _generate_section_index(
                    sub_dir, str(rel), title,
                    f"Documentation for {title.lower()}.",
                )
                if idx:
                    generated.append(idx)

    logger.info("Generated %d index pages", len(generated))
    return generated


def _generate_main_index(docs_dir: Path, project_name: str) -> Path | None:
    """Generate the main docs/index.md."""
    index_path = docs_dir / "index.md"
    if index_path.exists():
        return None  # Don't overwrite

    # Count generated pages
    gen_dir = docs_dir / "generated"
    page_count = 0
    if gen_dir.exists():
        page_count = len(list(gen_dir.rglob("*.md")))

    content = f"""# {project_name}

Welcome to the auto-generated documentation for **{project_name}**.

## Documentation Sections

| Section | Description |
|---|---|
| [Getting Started](generated/user/index.md) | User guides and tutorials |
| [Developer Guide](generated/developer/index.md) | Technical documentation |
| [API Reference](generated/api/index.md) | API endpoints and schemas |
| [Manual](manual/index.md) | Manually maintained pages |

---

*Auto-generated by mkdocsOnSteroids. {page_count} pages generated.*
"""
    docs_dir.mkdir(parents=True, exist_ok=True)
    index_path.write_text(content, encoding="utf-8")
    return index_path


def _generate_section_index(
    section_dir: Path,
    section_rel_path: str,
    title: str,
    description: str,
) -> Path | None:
    """Generate an index.md for a section directory."""
    index_path = section_dir / "index.md"
    if index_path.exists():
        return None

    # List all markdown files in this section
    pages: list[tuple[str, str]] = []
    for md_file in sorted(section_dir.glob("*.md")):
        if md_file.name == "index.md":
            continue
        page_title = md_file.stem.replace("-", " ").replace("_", " ").title()
        pages.append((page_title, md_file.name))

    # List subdirectories
    subdirs: list[tuple[str, str]] = []
    for subdir in sorted(section_dir.iterdir()):
        if subdir.is_dir():
            dir_title = subdir.name.replace("-", " ").replace("_", " ").title()
            count = len(list(subdir.glob("*.md")))
            subdirs.append((dir_title, f"{subdir.name}/index.md", count))

    content = f"# {title}\n\n{description}\n\n"

    if pages:
        content += "## Pages\n\n"
        for page_title, filename in pages:
            content += f"- [{page_title}](./{filename})\n"
        content += "\n"

    if subdirs:
        content += "## Sections\n\n"
        for dir_title, dir_index, count in subdirs:
            content += f"- [{dir_title}](./{dir_index}) ({count} pages)\n"
        content += "\n"

    section_dir.mkdir(parents=True, exist_ok=True)
    index_path.write_text(content, encoding="utf-8")
    return index_path
